### ISSUE TITLE
Short-term milestones

### ISSUE THREAD

**Issue by c4pt0r** [c4pt0r/tcli#20]
Some short-term milestone of tcli:

- [x] Basic KV commands support: get/set/delete/scan/count/...
- [x] CSV import/restore
- [x] Basic benchmark: ycsb
- [x] Variable support
- [ ] RawKV mode (WIP)
- [ ] JSON value via json-path: jget/jput/jscan (WIP)
- [ ] RESTFul API server
- [ ] Cluster info/operation
- [ ] Better commnad completetion
